### ISSUE TITLE
Request to commit a fix in order to prevent range check error in X11

### ISSUE THREAD

**Issue by infologick** [graemeg/fpGUI#101]
Hello,

Could you make 3 small modifications (adding a lower limit 0, with the Max function) in fpg_x11.pas, please?

```
procedure TfpgX11Canvas.DoFillRectangle(x, y, w, h: TfpgCoord);
begin
  XFillRectangle(xapplication.display, FDrawHandle, Fgc, x, y, Max(w,0), Max(h,0));
end;
```
Indeed, if a window (normal, or a dialog) is resized too small, then some controls, such as the TfpgGrid, can cause a range error: 
the calls to Canvas.FillRectangle(r); are made with negative ClipRect width or height (in particular TRects that go virtually further towards the right-width or towards the bottom-height of the parent window border).

This modification (setting a floor to 0, with Max) should be done, amo, in the same way in the 3 methods in fpg_x11.pas, that call XFillRectangle, i.e:
- DoFillRectangle (as explained above)
- DoXORFillRectangle 
- DoDrawImagePart 

ps: my Xorg -version = X.Org X Server 1.20.8.

Regards.

**Comment by graemeg** [comment]
Thanks for reporting this. I've fix the issue on both the `develop` and `maint` branches. I also double checked other X11 graphics calls and fix the same issue with **XFillArc()** call too. Please do a _git pull_ for the latest changes.
