### ISSUE TITLE
Golang Bindings?

### ISSUE THREAD

**Issue by nilopaim** [graemeg/fpGUI#107]
Has anyone tried to do this and allow the library to be used as GUI in Golang programs?

**Comment by fredvs** [comment]
Hello.

Are talking about fpGUI as native (or Java) library that can be used by application written in C, Go, Java, etc that can deal with native libraries?

If yes, then you may take a look at https://github.com/fredvs/fpGUIlib.
This is the universal library version of fpGUI widget set.

Fre;D

**Comment by nilopaim** [comment]
@fredvs Thanks for the information. I'll try it.

**Comment by fredvs** [comment]
@nilopaim This library version works only with fpGUI-**maint** branch: https://github.com/graemeg/fpGUI/tree/maint  (In the last commit time, the _fpGUI-develop_ branch was the _fpGUI-maint_ branch of now).

So to compile _libfpgui_ library, edit  _/fpGUIlib/src/extrafpc.cfg_ and change the path according to your system:

```
-fPIC
-Fi/home/you/fpGUI-maint/src/
-Fi/home/you/fpGUI-maint/src/corelib/
-Fi/home/you/fpGUI-maint/src/corelib/x11/
-Fu/home/you/fpGUI-maint/src/
-Fu/home/you/fpGUI-maint/src/corelib/
-Fu/home/you/fpGUI-maint/src/gui/
-Fu/home/you/fpGUI-maint/src/corelib/x11/
-Fu/home/you/fpGUI-maint/src/3rdparty/regex/
-FUunits/
-FE./
```
Then load+compile the project _/fpGUIlib-master/src/fpgui.lpi_
This will produce _libfpgui.so(dll)_ that you may use with Golang.

Good luck.

[EDIT] Note that I did not test it yet for Windows, only for Linux.
If you are interessed by fpGUI library for Windows, I can take a look  to make it work.
In last commit of today, changed infos about the fpGUI-maint branch needed.

**Comment by fredvs** [comment]
@nilopaim I dont know how Golang deals with native libraries.

There are demos of fpGUIlib used by Python, Java and fpc.

Maybe you will need to create a header, like for C or fpc.
If so take a look at code of _demo_fpc_ for the header and the program how to use the library.

Fre;D

**Comment by nilopaim** [comment]
@fredvs No success in compiling for Windows (Windows 10 64 bits). No errors are shown but the dll is not generated. 

As I have time commitments in doing an implementation of my work, I'll temporarly give up.

But for sure I'll return to try use your library. I think it is a very interesting and promising piece of software.

**Comment by fredvs** [comment]
Hello.

OK, I will try it on Windows 10 (tested today with last commit on Linux 64 and it is ok).

**Comment by fredvs** [comment]
Indeed, compiling fpGUI application with _fpGUI-main_ on Windows gives that error:
(this for pure-fpGUI apps too).

```
Z:\home\fred\fpGUI-maint\src\corelib\gdi\fpg_oledragdrop.pas(113,23) Error: (5042) No matching implementation for interface method "SetData(const tagFORMATETC;var TagSTGMEDIUM;LongBool):LongInt; StdCall;" found
Z:\home\fred\fpGUI-maint\src\corelib\gdi\fpg_oledragdrop.pas(203,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted

```

I created a issue for this
https://github.com/graemeg/fpGUI/issues/108

**Comment by nilopaim** [comment]
@fredvs As I said, I've got no errors from compilation. But it doesn't generate the dll.

**Comment by fredvs** [comment]
Hello.

Ok, with last commit it works now.

Here binaries Win32/64 of the fpc demo program using libfpgui.dll

[fpgui_lib_win32.zip](https://github.com/graemeg/fpGUI/files/6556870/fpgui_lib_win32.zip)
[fpgui_lib_win64.zip](https://github.com/graemeg/fpGUI/files/6556871/fpgui_lib_win64.zip)

[EDIT] And here the binaries of Linux 32/64 of the demo using libfpgui.so.
[fpguilib_lin32.zip](https://github.com/graemeg/fpGUI/files/6557427/fpguilib_lin32.zip)
[fpguilib_lin64.zip](https://github.com/graemeg/fpGUI/files/6557426/fpguilib_lin64.zip)



Note that here on Wine the 64 bit version is not always refreshed.

**Comment by fredvs** [comment]
> But it doesn't generate the dll.

Hum, strange, here it works.
What command line do you use to compile the library ?

**Comment by fredvs** [comment]
When compiling the library using _/fpGUIlib/src/fpgui.lpi_ the generated dll should be in _/fpGUIlib/src/libfpgui.dll_

**Comment by nilopaim** [comment]
> Hello.
> 
> Ok, with last commit it works now.
> 
> Here binaries of the demo Win32/64 of the fpc demo program using libfpgui.dll
> 
> [fpgui_lib_win32.zip](https://github.com/graemeg/fpGUI/files/6556870/fpgui_lib_win32.zip)
> [fpgui_lib_win64.zip](https://github.com/graemeg/fpGUI/files/6556871/fpgui_lib_win64.zip)
> 
> Note that here on Wine the 64 bit version is not always refreshed.

Using this it works.

A strange thing is that the download of the repo I did doesn't have  _/fpGUIlib/src/fpgui.lpi_

**Comment by fredvs** [comment]
> A strange thing is that the download of the repo I did doesn't have /fpGUIlib/src/fpgui.lpi

From where did you download the repo ?

Note that this project was more a exploration-test, not all the widgets are implemented.
Also I did test it for Java, C, Python and Pascal apps.
No idea if it could work with Golang.

**Comment by nilopaim** [comment]
> @nilopaim This library version works only with fpGUI-**maint** branch: https://github.com/graemeg/fpGUI/tree/maint (In the last commit time, the _fpGUI-develop_ branch was the _fpGUI-maint_ branch of now).
> 
> So to compile _libfpgui_ library, edit _/fpGUIlib/src/extrafpc.cfg_ and change the path according to your system:
> 
> ```
> -fPIC
> -Fi/home/you/fpGUI-maint/src/
> -Fi/home/you/fpGUI-maint/src/corelib/
> -Fi/home/you/fpGUI-maint/src/corelib/x11/
> -Fu/home/you/fpGUI-maint/src/
> -Fu/home/you/fpGUI-maint/src/corelib/
> -Fu/home/you/fpGUI-maint/src/gui/
> -Fu/home/you/fpGUI-maint/src/corelib/x11/
> -Fu/home/you/fpGUI-maint/src/3rdparty/regex/
> -FUunits/
> -FE./
> ```
> 
> Then load+compile the project _/fpGUIlib-master/src/fpgui.lpi_
> This will produce _libfpgui.so(dll)_ that you may use with Golang.
> 
> Good luck.
> 
> [EDIT] Note that I did not test it yet for Windows, only for Linux.
> If you are interessed by fpGUI library for Windows, I can take a look to make it work.
> In last commit of today, changed infos about the fpGUI-maint branch needed.

From this...

**Comment by fredvs** [comment]
Oooops, indeed, it is the code for Linux.

For Windows, please change all the _corelib/x11_/ with _corelib/gdi/_

Like this, edit _/fpGUIlib/src/extrafpc.cfg_ and change the path according to your system:

```
-fPIC
-Fi/home/you/fpGUI-maint/src/
-Fi/home/you/fpGUI-maint/src/corelib/
-Fi/home/you/fpGUI-maint/src/corelib/gdi/
-Fu/home/you/fpGUI-maint/src/
-Fu/home/you/fpGUI-maint/src/corelib/
-Fu/home/you/fpGUI-maint/src/gui/
-Fu/home/you/fpGUI-maint/src/corelib/gdi/
-Fu/home/you/fpGUI-maint/src/3rdparty/regex/
-FUunits/
-FE./

```

**Comment by fredvs** [comment]
Also, please use the last commits from https://github.com/fredvs/fpGUIlib/.

**Comment by graemeg** [comment]
Seem a solution was found in the end.
