### ISSUE TITLE
fpGUI Widgetset for macOS

### ISSUE THREAD

**Issue by Alexey-T** [graemeg/fpGUI#109]
It will be interesting to compile my app for macOS on fpGUI, WS, this way I may overcome some issues of the Cocoa WS. Will it be possible?

**Comment by Alexey-T** [comment]
Any update on this? Please...

**Comment by graemeg** [comment]
fpGUI doesn't support native Cocoa rendering, but you can for some years now, compile for MacOS, and with XQuartz, run your fpGUI applications. XQuartz used to come standard with MacOS, but was removed from the last few releases of OSX, so now you have to manually install XQuartz.

https://www.xquartz.org/

**Comment by JonnyTech** [comment]
Thanks @graemeg for the tip, I was asked about MacOS only last week.. Is there a roadmap for native cocoa rendering? I do not have an Apple device but is there anything that can be done to help implement it?

**Comment by graemeg** [comment]
I know it's an old thread, but just wanted to let you know that fpGUI 2.x release now has a native MacOS cocoa backend.
