### ISSUE TITLE
Drawing with Cairo in a fpGUI window

### ISSUE THREAD

**Issue by rchastain** [graemeg/fpGUI#124]
Hello Graeme and other!

I tried to compile the fpGUI examples included in [luipack](https://github.com/blikblum/luipack/tree/master/cairo/demos/fpgui).

I didn't use Lazarus (didn't know where to find the fpGUI package and wasn't really interested) but command line:

```
mkdir -p units
fpc @extrafpc.cfg basic.pas &> build.log
```
```
# extrafpc.cfg
-FUunits
-Fu/home/roland/Documents/pascal/sources/fpgui/lib/x86_64-linux
-Fu/home/roland/Documents/pascal/sources/luipack/cairo/fpgui
-Fu/home/roland/Documents/pascal/sources/luipack/cairo/classes
```

First I got this error:

```
Free Pascal Compiler version 3.2.0 [2020/07/05] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling basic.pas
Compiling /home/roland/Documents/pascal/sources/luipack-original/cairo/fpgui/cairofpgui.pas
Compiling /home/roland/Documents/pascal/sources/luipack-original/cairo/classes/cairoclasses.pas
Compiling /home/roland/Documents/pascal/sources/luipack-original/cairo/classes/objectavltree.pas
cairoclasses.pas(304,5) Warning: Constructor should be public
cairo_x11.inc(6,43) Error: Identifier not found "TfpgCanvasImpl"
cairo_x11.inc(6,43) Error: class type expected, but got "<erroneous type>"
cairo_x11.inc(9,52) Error: Identifier not found "TfpgApplicationImpl"
cairo_x11.inc(9,52) Error: class type expected, but got "<erroneous type>"
cairo_x11.inc(18,20) Warning: Symbol "Display" is not portable
cairo_x11.inc(19,5) Warning: Class types "TfpgCanvas" and "TX11CanvasAccess" are not related
cairo_x11.inc(19,30) Error: identifier idents no member "DCHandle"
cairo_x11.inc(20,5) Warning: Class types "TfpgApplication" and "TX11ApplicationAccess" are not related
cairo_x11.inc(20,43) Error: identifier idents no member "DefaultVisual"
cairofpgui.pas(150) Fatal: There were 6 errors compiling module, stopping
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

So I added `fpg_interface` in _cairo_x11.inc_.

After that I could compile the program, with a warning:

```
Free Pascal Compiler version 3.2.0 [2020/07/05] for x86_64
Copyright (c) 1993-2020 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling basic.pas
Compiling /home/roland/Documents/pascal/sources/luipack/cairo/fpgui/cairofpgui.pas
Compiling /home/roland/Documents/pascal/sources/luipack/cairo/classes/cairoclasses.pas
Compiling /home/roland/Documents/pascal/sources/luipack/cairo/classes/objectavltree.pas
cairoclasses.pas(304,5) Warning: Constructor should be public
cairo_x11.inc(18,20) Warning: Symbol "Display" is not portable
cairo_x11.inc(19,5) Warning: Class types "TfpgCanvas" and "TX11CanvasAccess" are not related
cairo_x11.inc(20,5) Warning: Class types "TfpgApplication" and "TX11ApplicationAccess" are not related
Compiling /home/roland/Documents/pascal/sources/luipack/cairo/classes/cairoutils.pas
Linking basic
2585 lines compiled, 3.1 sec
4 warning(s) issued
```

When I run the examples, there is a line in _stderr_ about an unhandled event:

```
fpGUI/X11: Unhandled X11 event received:  #65
```

But all the examples work.

![clock-linux](https://user-images.githubusercontent.com/13957204/216276554-b82286ec-ba84-4f82-8c7c-601b9225169d.png)

Maybe we could help the author of _luipack_ to update his fpGUI examples? And why not include a Cairo demo in fpGUI?

ASAP I will do the same experiment under Windows.

Regards.

Roland

Here are my files: [fpgui-cairo-examples.zip](https://github.com/graemeg/fpGUI/files/10567011/fpgui-cairo-examples.zip)

@blikblum

**Comment by blikblum** [comment]
Hi,

The compiler warnings are not an issue.

not sure about this: fpGUI/X11: Unhandled X11 event received:  #65

Please open a PR in luipack repository with fpg_interface change so i can merge

**Comment by rchastain** [comment]
Hi. Thanks for your answer.

> The compiler warnings are not an issue.

OK.

> Please open a PR in luipack repository with fpg_interface change so i can merge

Yes, I will do it, but I wanted to know the experts' opinion before. :)

And I intended to make a test on Windows, to see if the same solution works. (Now I am at home where I don't have Windows.)

**Comment by rchastain** [comment]
Made the same change for Windows. It fixes the compilation error.

But the examples don't work very well. I have to minimize and restore the window for the Cairo drawing to be displayed correctly (tested under Windows 32-bit). But it is probably a fpGUI issue, not related to luipack.

I attach the binaries in case someone would test.

[cairo-examples-binaries-windows32.zip](https://github.com/graemeg/fpGUI/files/10667450/cairo-examples-binaries-windows32.zip)

**Comment by rchastain** [comment]
> But the examples don't work very well. I have to minimize and restore the window for the Cairo drawing to be displayed correctly (tested under Windows 32-bit).

As a temporary solution, I applied the trick given by Fred [here](https://gitlab.com/rchastain/eschecs/-/issues/47#note_1229688777), and it works fine.

![fpgui-cairo-windows](https://user-images.githubusercontent.com/13957204/217294783-1b96eb17-4d72-46b8-8b67-73e638fffad5.png)

**Comment by rchastain** [comment]
I close the issue.
