### ISSUE TITLE
TfpgStringGrid scrolling erro with tiOPF

### ISSUE THREAD

**Issue by nelinnemann** [graemeg/fpGUI#29]
Hello

I'm trying to create a small demo application to learn tiOPF and fgGUI and fpTest (thx for all the tools btw).

I'm following this guide http://tiopf.sourceforge.net/Doc/PersistingObjectsAndRelationships/SimpleCollection/ and adapting things as I go to fit fpGUI and fptest.

Im at a point where I start to implement the GUI part and using the TfpgStringGrid to diplay my data.

Well here is the problem, when the TfpgStringGrid is too narrow a scroll bar appears at the bottom.
Scrolling to the right to see the next header gives me this error.

![2015-08-20 18_46_58-debugger exception notification](https://cloud.githubusercontent.com/assets/1086314/9389657/7ec414b8-476c-11e5-8a2f-8f02d18a1471.png)
![2015-08-20 18_47_19-source editor](https://cloud.githubusercontent.com/assets/1086314/9389658/7ecf1962-476c-11e5-83c9-06b983eea23e.png)

I've double checked with the code and if I make the TfpgStringGrid wider than the headers no errors. Is this a bug or an implementation error?

If I do it with DEMO 8 of the tiOPF repository and make the TfpgStringGrid narrower (50px) I get the exact same error.

You can find my code here if interested https://bitbucket.org/linnemann/adrsbook

Best regards

**Comment by graemeg** [comment]
Indeed, you did find a bug in the fpGUI stringgrid - I'll fix that ASAP. A quick work-around is to simply enable SmoothScrolling in the StringGrid.Options property.

Here is a zip archive with 5 patches that applies the work-around, and tweaks a few other things.
  http://geldenhuys.co.uk/~graemeg/temp/adrsbook_changes.zip

**Comment by nelinnemann** [comment]
Hey man.

Thx a bunch, I'll go through those nice additions.

Still new to the whole MGM and decoupling, takes some getting used to and digging through code to find the solutions.

Once done I'll fork the tiOPF and give you a pull request to add the code to demos if interested.
I do not know if thats the best place as it also includes fpTest and fpGUI so dont know where it fits best.

**Comment by graemeg** [comment]
If you want background information on MGM, I've written an introductory article a couple years back. It was how I started the MGM implementation in tiOPF, but obviously the tiOPF version has improved much. The article gives some useful background though.

  http://geldenhuys.co.uk/articles/

Yes, I would very much appreciate the project contribution. I'm working my way through my open source projects todo lists. One of them is updating the tiOPF website content. The framework has evolved and improved, but the info on the website was left behind. :-/

**Comment by graemeg** [comment]
The "Index out of bounds" should no be resolved. As of commit ad973c4.
