### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by JonnyTech** [graemeg/fpGUI#37]
I know that FPC final executable file sizes can be big compared to something similar written in other languages, but just looking for some input on reducing file sizes of executables created by fpGUI.

I am running Linux and using the following command-line to compile:

`fpc -Fu../lib/\$fpctarget -Xs -XX -CX -O4 test.lpr`

Is there anything else that I can do to reduce file size (strip is not necessary here as the arguments above already implement it)?

**Comment by graemeg** [comment]
The <fpgui>/lib/ directory contains fpGUI compiled units with debug information enabled. That _lib_ directory is simply to make compiling the examples easier, or while developing your own applications. FPC's smartlinking cannot function in that case. Bottom line - **don't use it for RELEASE builds**.

If you do want to create smaller binaries (eg: for RELEASE builds), specify the Unit and Include source folders directly - which in turn allows FPC to do it's job correctly by smartlinking only code that is needed by your application and striping debug information.

For example, here is a compile script I use under FreeBSD to create a release version of a project. Note that if you compile under Windows, or include AggPas, you need to tweak the paths slightly.

```
/data/devel/fpc-2.6.4/x86_64-freebsd/bin/fpc
 -Fi/data/devel/fpgui/src/
 -Fi/data/devel/fpgui/src/corelib/
 -Fi/data/devel/fpgui/src/corelib/x11/
 -Fu/data/devel/fpgui/src/corelib/
 -Fu/data/devel/fpgui/src/corelib/x11/
 -Fu/data/devel/fpgui/src/gui/
 -FUunits/x86_64-freebsd/
 -l -Mobjfpc -Sch -O2 -XX -Xs -CX -o../_bin/bugcollector.exe bugcollector.lpr
```

You can also place all the FPC command line parameters (or at least most of them) into a text file with one parameter per line, and then reference that text file when you compile your application. That is like what the fpGUI demos do.

For example:

```
fpc @extrafpc.cfg -O2 -o../_bin/bugcollector.exe bugcollector.lpr
```

ps: 
  As far as I know the -O4 command line parameter could produce bug executables, and I was told to use -O3 as the maximum optimisation level.

If I remember correctly, the last time I tried to create a small as possible executable, I managed to get a 32-bit Linux executable with five different widgets down to a mere 600KB. That is massively smaller that any GTK or Qt application, which requires many MB's of support libraries. fpGUI only needs the bare bones Xlib or GDI.

**Comment by JonnyTech** [comment]
Thanks Graeme

Here is my release.cfg:

```
-Fi../src/corelib/x11/
-Fi../src/gui/
-Fu../lib/$fpctarget
-Mobjfpc
-Sch
-O3
-XX
-Xs
-CX
```

Compiling like this:

```
fpc @release.cfg test.lpr
Free Pascal Compiler version 3.0.0+dfsg-6 [2016/06/02] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling test.lpr
Compiling /opt/fpGUI/src/corelib/fpg_base.pas
Compiling /opt/fpGUI/src/corelib/x11/fpg_impl.pas
Fatal: I/O error: File not open
Error: /usr/bin/ppcx64 returned an error exitcode
```

The code is bare right now, no code of note.

Any ideas?

**Comment by JonnyTech** [comment]
Sorry, my bad, I reinstalled fpGUI but forgot to build.

Compile now works:

```
fpc @release.cfg test.lpr
Free Pascal Compiler version 3.0.0+dfsg-6 [2016/06/02] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling test.lpr
Linking test
/usr/bin/ld.bfd: warning: link.res contains output sections; did you forget -T?
43 lines compiled, 0.4 sec
```

But the file size is exactly the same as before when building as debug.

Is there anything else to try? The files are not big big but would like any reduction possible.

**Comment by graemeg** [comment]
**Don't use the _lib_ directory at all for release builds.**
Replace

```
-Fu../lib/$fpctarget
```

with

```
-Fu../src/corelib/
-Fu../src/corelib/x11/
-Fu../src/gui
```

When FPC compiles the _lib_ directory via the scripts is _src_, it only compiles the fpGUI Toolkit units and doesn't know anything about your application, so it can't do any smartlinking because it things ALL fpGUI units are needed.

**Comment by JonnyTech** [comment]
But I don't have

`-Fu../lib/$fpctarget`

Mine is upper-case U:

`-FU../lib/$fpctarget`

If I take away the line with lib:

```
-Fi../src/corelib/
-Fi../src/corelib/x11/
-Fi../src/gui/
-Fu../src/corelib/
-Fu../src/corelib/x11/
-Fu../src/gui/
-Mobjfpc
-Sch
-O3
-XX
-Xs
-CX
```

 then this happens:

```
fpc @release.cfg test.lpr
Free Pascal Compiler version 3.0.0+dfsg-6 [2016/06/02] for x86_64
Copyright (c) 1993-2015 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling test.lpr
Compiling /opt/fpGUI/src/corelib/fpg_base.pas
Compiling /opt/fpGUI/src/corelib/x11/fpg_impl.pas
Compiling /opt/fpGUI/src/corelib/fpg_main.pas
Compiling /opt/fpGUI/src/corelib/fpg_constants.pas
fpg_constants.pas(98,4) Fatal: Cannot open include file "VERSION_FILE.inc"
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
```

Thanks for your patience so far...

**Comment by graemeg** [comment]
The compiler error is because FPC can't find the VERSION_FILE.inc which is located in the < fpgui >/src directory. Add the following to your release.cfg file:

```
-Fi../src/
```

The -Fu command line parameter specifies Source Search Paths, where FPC will be looking for _.pas files. The -FU is the Unit Output directory, where FPC will place compiled units (_.ppu etc files). I'm not sure if you mixed things up there, if so, just make sure your < fpgui >/src/ directory doesn't now contain any *.ppu files - if so, recursively delete them all from the _src_ directory.

Also if you specify -FU< unit_output_directory > then make sure that directory exists. FPC does not create directories during compilation.

**Comment by JonnyTech** [comment]
OK, got it finally, thanks, but the whole process only stripped 15k from the executable. Do I just have to live with it?

I remember developing on Win32. With Delphi I was getting large file sizes. Switched to [KOL](http://wiki.freepascal.org/KOL) and got down to one tenth of the size. Was hoping to do something similar here.

**Comment by graemeg** [comment]
Well, this is what I get with one of the fpGUI examples. It went from a 7.6MB executable (with debug information) down to a 0.8MB (release build) executable. This was under 64-bit FreeBSD which generatel have large executables than 32-bit platforms. Also, I was using the **_develop_** branch. The **_maint_** branch should generate slightly smaller executables.

```
[alignment (develop)]$ ls -lh
total 4040
-rwxr-xr-x  1 graemeg  graemeg   815K 18 Jul 17:45 aligntest-release.exe
-rwxr-xr-x  1 graemeg  graemeg   7.6M 18 Jul 17:46 aligntest.exe
-rw-r--r--  1 graemeg  graemeg   1.7K 28 Mar 12:10 aligntest.lpi
-rw-r--r--  1 graemeg  graemeg   2.2K 14 Jul 23:00 aligntest.lpr
-rw-r--r--  1 graemeg  graemeg   434B 14 Aug  2015 aligntest.lps
-rw-r--r--  1 graemeg  graemeg    26K 18 Jul 17:39 aligntest.o
-rw-r--r--  1 graemeg  graemeg    16K 16 Apr 13:25 aligntest.prj
-rw-r--r--  1 graemeg  graemeg    77B 28 Mar 12:10 extrafpc.cfg
-rw-r--r--  1 graemeg  graemeg   231B 18 Jul 17:43 release.cfg
drwxr-xr-x  2 graemeg  graemeg     4B 18 Jul 17:45 units
```

**Comment by JonnyTech** [comment]
Understood, thank you very much for taking the time to explain everything. It's a great project that you have here and I shall be experimenting as I have more time. Is this the best place to ask questions?

PS I just looked at the branches, do you mean develop rather than maint?

**Comment by graemeg** [comment]
For support, please use the official support news group (NNTP server). Details on how to connect can be seen here [http://fpgui.sourceforge.net/support.shtml].

The "maint" branch should produce slightly smaller binaries - it is also the stable version of fpGUI Toolkit. So if you are starting off with fpGUI, I suggest you use that for now. The "develop" branch is the unstable work. We have had some significant branches merged into "develop" recently, and I'm busy working on getting that code well integrated and more stable before the next major release.
