### ISSUE TITLE
About TfpgStyle status

### ISSUE THREAD

**Issue by lainz** [graemeg/fpGUI#41]
Hi, I want really to theme all the components inside fpGUI.
I'm making my own components for now because TfpgStyle is not complete.

But I have currently a problem: I can't create a proper descendant of TfpgComboBox because it uses TfpgListBox and I can't theme that.

For example: myComboBox is descendant of TfpgComboBox that uses TfpgListBox, if I want to use myListBox I cant-

To theme the control I must copy all that is inside the control to my own unit and rename it. That is not a good idea because I'm missing component updates only for theming it.

So the idea is to have a proper TfpgStyle to handle all theming outside and nothing inside the controls.

I can help in any way? Like moving the control theming to the TfpgStyle?

Hope I'm clear if not please tell me.

Edit: I made almost a full theme using the develop branch, but hope there are more theming options instead of using bitmaps for CheckBox and RadioButton.

**Comment by graemeg** [comment]
Apologies for the late reply - I have been away on holiday.  You raised a known issue - the fpGUI theming is not 100% complete yet. I will appreciated any contributions towards this goal - moving widget rendering code to the theming classes. In the mean time I have disabled the hard-coded BlueCurve theme code used by TfpgListBox.

I might also have a local branch where I did some more theming changes. I'll double check on my computers and VM's I have available. If I find it, I'll merge it in ASAP.

**Comment by graemeg** [comment]
I've just committed same changes that makes TfpgListBox themable via two new fpgStyle API calls. I've tested it by modifying the "customstyles" demo (changes also committed). Please take a look at the demo to see how it is used. If you need any further amendments to the fpgStyle API please let me know.

**Comment by lainz** [comment]
Many thanks for your time.
