### ISSUE TITLE
fpgStyle DrawDirectionArrow

### ISSUE THREAD

**Issue by lainz** [graemeg/fpGUI#42]
This code works on master branch but does not produce the same result on develop branch, any ideas? The arrow get's broken.

``` pascal
fpgStyle.DrawDirectionArrow(Canvas, Width - 8 - 6, (Height - 6) div 2, 8, 6, adDown);
```

Develop branch:
![trianglebug](https://cloud.githubusercontent.com/assets/4131395/17087202/d65c23f4-51da-11e6-906d-c3a5a38cb12b.PNG)

Master branch:
![triangleright](https://cloud.githubusercontent.com/assets/4131395/17087201/d65b33a4-51da-11e6-93f3-b9d93a7be876.PNG)

**Comment by graemeg** [comment]
Thanks for reporting the issue. Please get an update and retest. The GDI code had one too many polygon points.

**Comment by lainz** [comment]
Thankyou it works fine!
