### ISSUE TITLE
Invalidate area in inherited Edit

### ISSUE THREAD

**Issue by lainz** [graemeg/fpGUI#43]
Hi, I'm creating an edit control that inherits from fpgEdit.

The main problem is in 'develop' branch: the area isn't fully invalidated, see image attached. I get a gap of 1px sometimes at the upper part, some at the bottom. Sometimes the focus rect remains at the top, sometimes the focus rect remains half if I switch between 2 edits.

The blue part is the focus rect, currently not visible at bottom:
![rectbug](https://cloud.githubusercontent.com/assets/4131395/17267664/41dc483a-55e5-11e6-82be-1acd4212fabd.png)

If you consider it neccesary I can attach the source code of the custom edit control and a demo project.

Other problems:
- Edit doesn't support the caret

**Comment by lainz** [comment]
PD: I'm using the alpha mode using -AggCanvas option.
The caret doesn't works, check this line of code in caret class:
      FCanvas.XORFillRectangle($FFFFFF, FLeft, FTop, FWidth, FHeight);

**Comment by graemeg** [comment]
I've been away on holiday, so apologies for the late reply. I'll take a look at the problem tonight or tomorrow. Many thanks for reporting it. The caret painting is a known issue in the "develop" branch - I'll try and resolve that as soon as possible too.

If you read this before tonight or tomorrow, could you please attach the test project you mentioned and new custom control, so I'm sure I'm looking at the right thing.

**Comment by lainz** [comment]
Here it is: is the control
[kaaj_edit.zip](https://github.com/graemeg/fpGUI/files/409229/kaaj_edit.zip)

**Comment by lainz** [comment]
This is the whole thing:
https://github.com/bgrabitmap/kaajcontrols

Please test the edit control with the -AggCanvas and withouth, change focus between them to see the 'garbage' that produces sometimes (the whole control is not redrawn fully)
