### ISSUE TITLE
Sizeable broken in develop

### ISSUE THREAD

**Issue by JonnyTech** [graemeg/fpGUI#44]
I know that the develop branch is work in progress and that things may break, but I just wanted to point out the the form property "**Sizeable**" is broken on Linux (I do not have Windows to test it there).

**Comment by JonnyTech** [comment]
Following up, try the program which shows another issue linked to 'sizeable'.

[Example program - uploaded as .txt for GitHub filters](https://github.com/graemeg/fpGUI/files/409034/test.lpr.txt)

Compile and run it (my system is Linux64) then drag the form by the the **main area**, not the title bar.

If 'sizeable' is true (default) then you can drag the form correctly.

If 'sizeable' is false then when dragging it resizes to about 20x20px.

The master and main branches do not have this problem.

**Comment by graemeg** [comment]
Many thanks for the additional information. I appreciated any bug reports. I'll take a look at the problem tonight or tomorrow.

**Comment by JonnyTech** [comment]
Thank you too for getting back so soon, I did take a look at fpGUI's source but just got lost there!

My workaround it to set MinWidth and MaxWidth equal, and MinHeight and MaxHeight too, and leave Sizeable enable.

I wasn't sure whether to report this in the newsgroup but figured that development type bugs were better logged here.

**Comment by JonnyTech** [comment]
A follow up which links to issue #45 (concerning dialogs but now closed):

When a dialog is created, ie ShowMessage('OK')
- the dialog window is resizeable in develp which is incorrect
- the message text (OK from the above) disappears when resized

**Comment by graemeg** [comment]
I can't remember went, but the Sizeable issue has been fixed some time ago, I simply forgot to close this bug report. Just to confirm it, I downloaded your example app and retested. Sizeable set to True or False and the program functions exactly like it should.
