### ISSUE TITLE
TfpgX11Application.DoWaitWindowMessage and fpGUI-develop

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#46]
Hello Graeme.

There is a access violation after closing forms for all X11-projects with last fpgui-develop branch.

After debugging, it comes from:

`procedureTfpgX11Application.DoWaitWindowMessage(atimeoutms: integer)`-> in fpg_x11.pas

At line 2363: 
`w.DoWindowNetStateChanged;` -> access violation

This solves everything: 

```
if assigned(w) then  // this added
w.DoWindowNetStateChanged; 
```

Fre;D

**Comment by fredvs** [comment]
Oooops, you have fix it in last commit !
Thanks ;-)
Sorry for the noise.
Fre;D

**Comment by graemeg** [comment]
I'm glad you noticed it was fixed a few days ago. :-)
