### ISSUE TITLE
"gCommandLineParams" is deprecated

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#47]
Hello Graeme.

When compiling with develop-branch customstyles.lpr demo, there is that warning:

> customstyles.lpr(53,10) Warning: Symbol "gCommandLineParams" is deprecated: "Use fpgApplication's ICmdLineParams interface instead"

This because of that:

`if not gCommandLineParams.IsParam('style') then`

The same warning with mystyle.pas, edits_extrahint.lpr, custom_window.lpr.

OK, but how to use the ICmdLineParams-develop way... ?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello Graeme.

Ok, you give the solution in fpGUI forum:

```
var
 cmd: ICmdLineParams;   
...
 if Supports(fpgApplication, ICmdLineParams, cmd) then
  if not cmd.HasOption('style') then
...
```

Many thanks ;-)

Fre;D

**Comment by graemeg** [comment]
Glad I could help.

**Comment by fredvs** [comment]
PS: Dont forget to commit this in fpgui_develop for customstyles.lpr, mystyle.pas, edits_extrahint.lpr, custom_window.lpr.

Or do you want that I try to make it via git (but you know how I am afraid of him)?
Fre;D
