### ISSUE TITLE
develop branch and last Xorg.

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#52]
Hello.

Compile using last xorg-server-1.17.4,1 on FreeBSD 10.3 and fpGUI-develop is OK.

Sadly, when running, it crash at loading with this mesasge:

> X Error of failed request:  BadAtom (invalid Atom parameter)
>   Major opcode of failed request:  18 (X_ChangeProperty)
>   Atom id in failed request:  0x0
>   Serial number of failed request:  170
>   Current serial number in output stream:  171

This not appends with maint-branch.
Fre;D

**Comment by fredvs** [comment]
Hello.
I have tested with fpc 2.6.4 and same error message than with fpc 3.0.0

Fre;D

**Comment by andrewd207** [comment]
I haven't looked at this but XInternAtom has only_if_exist for the third param. If the third param is True then the "atom" that is returned will = 0 if it doesn't exist yet. Probably this is the problem.

**Comment by andrewd207** [comment]
Ok I found a couple of places this was the case. I commited a change in 5590fc728b629bb158d5fc2ae89b48f43865c3cb please let me know if this fixed it.

**Comment by fredvs** [comment]
Hello Andrew.

Sadly, on Linux Mint 64 bit, opacity does not work.

Here the message from compton when the fpGUI application is loaded:

> [    27.03 ] error 3 (BadWindow) request 2 minor 0 serial 11752 ("BadWindow (invalid Window parameter)")

For FreeBSD, I will test it asap.

Fre;D

**Comment by fredvs** [comment]
Yeeep, Andrew, for FreeBSD 64, it WORKS.

![opacity_fpgui](https://cloud.githubusercontent.com/assets/3421249/18371548/93e0c94c-7635-11e6-9f05-cfd90be433c4.jpg)

Many, many. many thanks.

Fre;D

**Comment by andrewd207** [comment]
Ok great! What changed from the last comment please? :)

Edit: I see, Linux Mint > FreeBSD

**Comment by fredvs** [comment]
> What changed from the last comment please? :)

Hum, sorry, I do not understand.
I just have try your last commit with Linux Mint 64 bit (without luck) and then (2 minutes later) on FreeBSD 64 bit (with full of luck).

Fre;D

**Comment by fredvs** [comment]
By the way, for me, it is much more important that it works for FreeBSD (polYdev).
So I am totally happy with your new commit.
But maybe Linux Mint users would want it too.

Fre;D

**Comment by andrewd207** [comment]
What are the window managers you use on the freebsd and linux systems?

**Comment by fredvs** [comment]
For FreeBSD --> JWM (opacity with your new commit works perfectly)
For Linux Mint --> It is the original window managers (not sure but I think it is Gnome, I have to google it).

Fre;D

**Comment by fredvs** [comment]
Re-hello.

I think that for Mint, it is the mate-window-manager.

Fre;D

**Comment by andrewd207** [comment]
Ok thanks, I will look into this later.

**Comment by fredvs** [comment]
Ok, many thanks Andrew, for me it is solved.

But, according with [(http://distrowatch.com)], Mint seems to be the most used Linux distro.

Fre;D

**Comment by JonnyTech** [comment]
I have Mint 18 64bit installed. Just tried with Cinnamon, Mate and XFCE. All working on my system.
Which version of kernel and which display driver is used? Please post output of following:

```
$ uname -a
$ lspci -vnn | grep VGA -A 12
$ glxinfo | grep -i "vendor\|rendering" 
$ lshw -c video
```

**Comment by fredvs** [comment]
Hello Jonny.

My Linux system is Mint 17 mate 64 bit.

**$ uname -a**
Linux fred-Lenovo-YOGA-300-11IBY 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**$ lspci -vnn | grep VGA -A 12**
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31](rev 0e) (prog-if 00 [VGA controller])
    Subsystem: Lenovo Device [17aa:3908]
    Flags: bus master, fast devsel, latency 0, IRQ 106
    Memory at d0000000 (32-bit, non-prefetchable) [size=4M]
    Memory at c0000000 (32-bit, prefetchable) [size=256M]
    I/O ports at 2050 [size=8]
    Expansion ROM at <unassigned> [disabled]
    Capabilities: <access denied>
    Kernel driver in use: i915

00:13.0 SATA controller [0106]: Intel Corporation Atom Processor E3800 Series SATA AHCI Controller [8086:0f23](rev 0e) (prog-if 01 [AHCI 1.0])
    Subsystem: Lenovo Device [17aa:3908]
    Flags: bus master, 66MHz, medium devsel, latency 0, IRQ 104

**$ glxinfo | grep -i "vendor|rendering"**
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Intel Open Source Technology Center

**$ sudo lshw -c video**
[sudo] password for fred: 
  *-display  
       description: VGA compatible controller
       product: Atom Processor Z36xxx/Z37xxx Series Graphics & Display
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 0e
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:106 memory:d0000000-d03fffff memory:c0000000-cfffffff ioport:2050(size=8)

After Googling, it seems that Linux 17 Mate (that uses mate-window-manager) is not able to render opacity.

So, for me, all is ok (and if I want opacity-rendering on my Linux mate system, I have to install a other window manager ;-) ).

Many thanks to Andrew for his fix and to Jonny for helping.

Fre;D

**Comment by fredvs** [comment]
@andrewd207 : For me all is ok and I think that I may close the issue.

Fre;D

**Comment by JonnyTech** [comment]
I had a very similar system to yours. The display driver was not working well with 64 bit systems (both Linux and Windows). A web search at the time revealed that there were never any working 64 bit drivers ever created. I installed 32 bit Linux and then everything worked including transparency effects.

**Comment by fredvs** [comment]
Ha, ok.
By the way, with FreeBSD 64 + JWM, composite and opacity work like charm.
