### ISSUE TITLE
uidesigner and TfpgCalendarCheckCombo

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#54]
Hello Graeme.

Maybe that could be changed (see wc.NameBase) :

```
 wc          := TVFDWidgetClass.Create(TfpgCalendarCheckCombo);
  wc.NameBase := 'CalendarCombo';
```

with this :

```
  wc          := TVFDWidgetClass.Create(TfpgCalendarCheckCombo);
  wc.NameBase := 'CalendarCheckCombo';
```

and with TfpgLabel, add AutoSize property:

  `wc.AddProperty('AutoSize', TPropertyBoolean, '');`

Fre;D

**Comment by graemeg** [comment]
- I consider both those calendar combo components, hence the same base name.
- I've adde the TLabel.AutoSize property to the UIDesigner.
