### ISSUE TITLE
Fix for your published "DEMO"

### ISSUE THREAD

**Issue by 3FLLC** [graemeg/fpGUI#57]
move:

      // Place button in bottom right corner.
      btnClose := CreateButton(self, Width-90, Height-35, 75, 'Quit', @btnCloseClick);
      btnClose.ImageName := 'stdimg.quit';
      btnClose.Anchors := [anRight, anBottom];

from MainForm.Create to MainForm.AfterCreate. Since you changed the way you set defaults, it looks like the Width/Height, are 10 by default.

**Comment by graemeg** [comment]
Thanks for reporting.... Which demo are you referring to?

**Comment by 3FLLC** [comment]
Links:

                https://en.wikipedia.org/wiki/FpGUI#Example_Program

 

                stdimglist – on FPC’s site, and others – I fixed the Wikipedia already :)

 

Ozz

**Comment by saulery** [comment]
It's already fixed in the code of fpGUI at : https://github.com/graemeg/fpGUI/blob/develop/examples/gui/stdimages/stdimglist.lpr

**Comment by graemeg** [comment]
Thanks, I updated the Afrikaans Wikipedia code sample as well.
