### ISSUE TITLE
Autoscale GUI elements to higher DPI

### ISSUE THREAD

**Issue by palikacska** [graemeg/fpGUI#59]
Is this supported?

So will a higher DPI cause fpGUI to scale all its GUI elements accordingly, or will it look messed up with labels too big to fit in a button, etc. ?

**Comment by graemeg** [comment]
fpGUI already has support for Hi-DPI environments for some years now. Saying that, I've always kept the support outside the framework via a separate unit to enable support, but just recently I decided to build it into the framework via the fpgApplication instance.

Here is the same 96dpi (designed) form displayed at various DPI values under Linux/FreeBSD:

96dpi designed app
- http://geldenhuys.co.uk/~graemeg/project2-96dpi.png

Now that same execuatble automatically scales depending on the end-user's DPI value. Note how everything stays in proportion.
- http://geldenhuys.co.uk/~graemeg/project2-80dpi.png
- http://geldenhuys.co.uk/~graemeg/project2-107dpi.png
- http://geldenhuys.co.uk/~graemeg/project2-120dpi.png
- http://geldenhuys.co.uk/~graemeg/project2-140dpi.png

And here is a similar test under Windows 8.

- http://geldenhuys.co.uk/~graemeg/temp/Win8_96dpi.png
- http://geldenhuys.co.uk/~graemeg/temp/Win8_120dpi.png
- http://geldenhuys.co.uk/~graemeg/temp/Win8_144dpi.png
- http://geldenhuys.co.uk/~graemeg/temp/Win8_192dpi.png

Under Windows 8+ you need to supply a Manifest file with your application to tell the OS how scaling is handled in the application here is an example of such a Manifest file. Again, this will be standard in fpGUI's code repository soon.

```xml
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3" >
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

For your convenience I've added that separate unit to the code repository (commit 71a8af3) until I can complete the built-in support (which is about 85% done)

**Comment by graemeg** [comment]
And this is all you need to do to use the toolbox unit.

```delphi
   const
     cDPI = 96;
   procedure TMainForm.FormShow(Sender: TObject);
   begin
     if fpgApplication.Screen_dpi <> cDPI then
       ScaleDPI(self, cDPI); // cDPI is the dpi you designed the form at
   end;
```

**Comment by palikacska** [comment]
That's just great. I was afraid that it's not supported. I didn't really know about that unit. Thank you very much! You're my hero. :)
