### ISSUE TITLE
fpGUI on Rpi3B with R2017-06-21-raspbian-jessie

### ISSUE THREAD

**Issue by fredvs** [graemeg/fpGUI#63]
Hello Graeme.

Using maint fpGUI on Raspberry Pi 3B, OS : R2017-06-21-raspbian-jessie and fp 3.0.2, I get trouble with the panel-taskbar.
The compilation is ok but, when running a fpGUI application, it close the raspbian-jessie panel-taskbar.
This for all fpGUI apps (including fpGUI demos).
I have to reboot to get the panel-taskbar back.

Here before to run a fpGUI app:
![fpgui_armrpi_taskbar_before](https://user-images.githubusercontent.com/3421249/29136886-df75c5c2-7d3e-11e7-9675-28c6201ac53d.jpg)

Here after:
![fpgui_armrpi_taskbar_after](https://user-images.githubusercontent.com/3421249/29136929-0145b8f6-7d3f-11e7-983a-73645b7e3c6e.jpg)

Thanks.

Fre;D

**Comment by fredvs** [comment]
Hello.

Fixed:
http://geldenhuys.co.uk/webnews/webnews.cgi?user=fredvs;group=fpgui.support;article=8200

Fre;D

**Comment by graemeg** [comment]
Fred... If you have the time, would you mind retesting the latest "maint" branch. I've made some improvements regarding the Window Icon handling (see last few commits).

**Comment by fredvs** [comment]
OK, I will (try to) find some time asap.
Write you later.
Fre;D

**Comment by fredvs** [comment]
Ooops, sorry Graeme but I forgot that I do not have any Rpi here.
I am on the road again and will be on earth in 2 months.
I only have my laptop with me.
So I could not test right now on a Rpi.

**Comment by graemeg** [comment]
No worries. I'll whip out my old RPi and see if I can get the thing going (haven't used it in 2-3 years).
