### ISSUE TITLE
geldenhuys.co.uk offline

### ISSUE THREAD

**Issue by JonnyTech** [graemeg/fpGUI#65]
@graemeg, fyi the support news server, well actually geldenhuys.co.uk, has been offline for a few days - I'm sure that you are aware but posting here so you can provide an update when it is back online..

**Comment by graemeg** [comment]
Oh wow, I have been so preoccupied with other stuff, I didn't actually know. Many thanks for reporting it. The website and news server should be back up and running again.

**Comment by JonnyTech** [comment]
Confirmed - thanks

**Comment by JonnyTech** [comment]
@graemeg, FYI geldenhuys.co.uk is offline again

**Comment by JonnyTech** [comment]
It is back online now

**Comment by graemeg** [comment]
Thanks for letting me know. I had a double whammy. I had an ISP outage, then the stupid Ubuntu auto-update kicked in and updated VirtualBox but did not restart any of the prior running VMs once the update was complete. :-( Guess I'll be disabling the auto-update service next.

**Comment by JonnyTech** [comment]
Another outage...

**Comment by graemeg** [comment]
Really? Looking at the logs I can see there was a 50Mbps drop in speed tonight (some or other negative spike), but that still left me with plenty of bandwith. No total outages. My DNS entries are all still correct and active across the globe too.

Can you still not connect?

![image](https://user-images.githubusercontent.com/72053/69276043-8e350380-0bd5-11ea-8b1a-5d84f9834b2a.png)

![image](https://user-images.githubusercontent.com/72053/69276083-a573f100-0bd5-11ea-811c-0e694e79fd62.png)

**Comment by JonnyTech** [comment]
It's up now, not sure when it came back online. I did try several times, in the space of about 10 minutes, earlier. Could not connect to the domain at all. Strange...
