### ISSUE TITLE
Readme tells about packages which dont exist in Ubuntu 17.4

### ISSUE THREAD

**Issue by Alexey-T** [graemeg/fpGUI#73]
```
user@user-Notebook:~$ sudo apt-get install libX11-dev
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libX11-dev
user@user-Notebook:~$ sudo apt-get install libXft-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libXft-dev

```

**Comment by fredvs** [comment]
Hello.

You may use dynamic loading of those libraries.
So no need of xxx.dev packages.

Take a look here:
https://github.com/fredvs/dynx

And here a fpGUI application using those dynamic loaded libraries:
https://github.com/fredvs/uidesigner_ext

Fre;D

**Comment by Alexey-T** [comment]
Why not fix readme?

**Comment by fredvs** [comment]
IMHO, it is not a fpGUI problem.
You should advice this to fpc mailing-list or fpc-bug tracker.
Fre;D

**Comment by Alexey-T** [comment]
This readme is on this github at the root.

**Comment by graemeg** [comment]
Thank you for reporting this Alexey-T - I don't always keep track of the latest Linux distro changes. They just love to break backwards compatibility. :-/ The new package names are the same as the old ones, just all lower-case. I have updated the README.txt file in both the **maint** and **develop** branches.

https://packages.ubuntu.com/artful/libx11-dev
https://packages.ubuntu.com/artful/libxft-dev
