### ISSUE TITLE
Compiler switches missing

### ISSUE THREAD

**Issue by mhekeler** [graemeg/fpGUI#75]
_I recently posted in another issue #70. But then I realised that this issue was closed and so I don´t know if anyone hears my noise in that ticket :-) So here comes a new ticket:_

I think another problem for a new user is that the file `extrafpc.cfg` with compiler switches is missing in the directory for the helloworld example.
The `compileall.sh` script requires this file for compiling `helloworld.lpr`
This can be solved by copying extrafpc.cfg from any example directory (no matter from which one)

```
cd examples/helloworld
cp ../menutest/extrafpc.cfg .
fpc @extrafpc.cfg helloworld.lpr

```

**Comment by graemeg** [comment]
That's strange... The "examples/corelib/helloworld/" project has had a extrafpc.cfg file since 2007-08-26.  Which branch are you working on?

**Comment by graemeg** [comment]
Ah, I see the examples/gui/ directory also has a "helloworld" project. I've added the missing *.cfg file in commit 04f93bd883. Thank for reporting the issue.
