### ISSUE TITLE
Usage help - where is the package for Lazarus 1.8 ?

### ISSUE THREAD

**Issue by iongion** [graemeg/fpGUI#76]
Hi, I am new to both Lazarus and fpGUI, what does one need to use this toolkit in Lazarus. I do not want to "draw" components, I want it to recognize the projects and be able to edit/debug. Currently I get an error about missing package "fpgui_toolkit". What can I do to make it work ?

**Comment by fredvs** [comment]
Hello.

Take a look at: https://github.com/graemeg/fpGUI/blob/maint/extras/lazarus_ide/readme.txt

> fpgui_ide.lpk
>   This package adds a new project type in the Lazarus IDE.
>   So you can then create a fpGUI based project by 
>   going: 'File | New' and selecting 'fpGUI Application'.

All Lazarus-stuff are in directory:  **/fpGUI/extras/lazarus_ide/**

Fre;D

**Comment by iongion** [comment]
Thank you!

**Comment by iongion** [comment]
Sorry, I have reopened this as now I have a new issue, when I try to load the project, it prompts me with:

The following unit failed to load *aggpas*

![example](https://user-images.githubusercontent.com/867609/36302356-6e183e2c-1308-11e8-8cb5-b67520f2ee2b.png)

**Comment by fredvs** [comment]
Hello.

Huh, I do not use Lazarus anymore but aggpas is a package that you can install via menu "package" + "install".

In a other way, if you have problem with Lazarus + fpGUI you may try **ideU**.
https://github.com/fredvs/ideU/releases

In **ideU** is included fpGUI Designer_ext, ready to use.
You only have to unzip the **ideU** project, run the **ideU** executable and define the root-path of fpGUI.

Fre;D

**Comment by graemeg** [comment]
Hi iongion.

The new fpGUI uses AggPas to do more advanced 2D software rendering, anti-aliasing and such. So there is a new dependency by default to the **aggpas.lpk** package found in **< fpgui >/src/corelib/render/software/** directory. Simply open the package once with Lazarus IDE using the menu "Package -> Open Package File (*.lpk)". Then try and recompile your project. and Lazarus should be able to find everything it needs.

The dependency on AggPas is still optional, but I haven't found a seamless way of adding/removing the package dependency with Lazarus IDE.

I hope that helps, and thanks for trying out fpGUI.

**Comment by iongion** [comment]
Thank you guys for your help, I am actually looking for using Pascal with an Agg implementation, so far, fpGUI seems to have it all. I am looking also to integrate https://github.com/SaschaWillems/dglOpenGL as it has some vendor extensions I will require. It seems fpGUI provides all I need!
Through my research, I found there are a few agg implementations, none of which is an up to date one.
Awesome work!
