### ISSUE TITLE
po files are not full

### ISSUE THREAD

**Issue by glixx** [graemeg/fpGUI#80]
uidesigner uses fpgui.lang.po for translations, but fpgui.lang.po does not contents resourcestrings from uidesigner/vfd_constants.pas.
Needs to add resourcestrings from uidesigner/vfd_constants.pas into fpgui.lang.po or use uidesigner.lang.po way.

**Comment by graemeg** [comment]
Only <fpgui\src\* units are part of the fpgui.*.po resource files. Any other applications (as would be any 3rd party applications created using fpGUI), a separate application specific .po files needs to be shipped.

For the UIDesigner application that would mean a list of the following files.

- uidesigner[.exe]
- fpgui.*.po
- uidesigner.*.po

If your application only supports one language translation, then no *.po files need to be shipped with the application. You can also toggle the default language that the fpGUI framework itself uses, by modifying the defines show in the _fpg_constants.pas_ unit.

Granted, the UIDesigner application has separated out all translatable resource strings into a separate unit (the first step in translating an application), but no other language translations exist for it, other than English. Contributions are welcome though.

**Comment by glixx** [comment]
Will you create POT file for uidesigner?

**Comment by glixx** [comment]
fixed by pull request https://github.com/graemeg/fpGUI/pull/86
Please merge.

**Comment by graemeg** [comment]
Merged your changes and created the same localization.{sh|bat} scripts like the fpGUI framework itself uses.
Many thanks for your contribution.
