### ISSUE TITLE
uidesigner's hints are empty

### ISSUE THREAD

**Issue by glixx** [graemeg/fpGUI#85]
![screenshot_20181121_151042](https://user-images.githubusercontent.com/2681872/48820204-fc49af00-ed64-11e8-8e67-eca0a3ffd7e1.png)
uidesigner's hints are empty after showing several hints.

there is bug https://github.com/graemeg/fpGUI/issues/49
but uidesigner can be fixed separately from fpgui.

**Comment by glixx** [comment]
I need patch to override "fpg_main, procedure TfpgApplication.ActivateHint(APos: TPoint; AHint: TfpgString);" by uidesigner

**Comment by graemeg** [comment]
Closed as it is a duplicate of bug #49 .

**Comment by graemeg** [comment]
Should be fixed now, with the latest code in the `develop` branch. :)
