### ISSUE TITLE
Question about a sample on your site.

### ISSUE THREAD

**Issue by davidbruce** [graemeg/fpGUI#93]
Hello I stumbled upon your gui toolkit and I have been digging through the samples.  I found some sample theme screenshots from the Lazarus wik and the last page is a music player: http://geldenhuys.co.uk/~graemeg/themes/image009.png

This music player looks nearly identical to the Elementary OS music player: https://github.com/elementary/music

Is the music player sample real?  Is the source code available?

**Comment by graemeg** [comment]
That was a prototype (clone) of the Elementry OS music player - so well spotted. :-)  It came about as I got criticized that fpGUI looks "outdated" and modern apps can't be created with it. I tried to explain that I personally like the Win2000 look, hence fpGUI defaults to that theme, but other themes are available, and indeed you can create more "modern/minimalist" looking apps. So I recreated the Elementry OS music player visually.

I should still have the code somewhere. I believe the start of it was included in the fpGUI examples under the gui/customwindow/ example. The full prototype (used for the screenshot) should be somewhere on my hard drive. It could play music too, via the UOS cross-platfrom sound library [https://github.com/fredvs/uos/].

I hope that answers your question.

**Comment by davidbruce** [comment]
Awesome it does!  I might take a stab at recreating it when I end up having time.  Is this a good medium for contacting you if I have questions or would email or some kind of forum be better?

**Comment by graemeg** [comment]
For anything fpGUI related, I prefer all discussions go into the [**fpgui.support**](http://fpgui.sourceforge.net/support.shtml) newsgroup - the official support channel for fpGUI.  

That way others can join the conversation, or you might even find others with mutual interest in a fpGUI based projects.
