### ISSUE TITLE
Commit request for a corrected version of WindowSetPropertyUTF8

### ISSUE THREAD

**Issue by infologick** [graemeg/fpGUI#99]
Hello, 

Many thanks for your impressive work.
Could you commit this patch into the file fpg_netlayer_x11.pas, please?

```
procedure TNETWindowLayer.WindowSetPropertyUTF8(const AWindow: TWindow;  AProperty: TAtom; ALength: Integer; UTF8Text: String);
begin
  if UTF8Text = '' then {check for an empty Pascal string, before: some versions of XChangeProperty launch a - possible silent - range checking error, if the string is empty; in this case, the Hint properties over controls are not displayed}
    Exit;

  XChangeProperty(FDisplay, AWindow, AProperty, UTF8_STRING, 8, PropModeReplace, @UTF8Text[1], ALength);
end;
```

suggestion: in the same unit, when there are calls to XChangeProperty, but with a PChar or an Ansistring parameter, it would probably be better to write the same test, before, like:
```
...\...
If Pointer(pAtThisPChar) = nil then Exit;

XChangeProperty(......, pAtThisPChar,...\...);
...\...
```

For information, my Linux tells me that Xorg -version = X.Org X Server 1.20.8.

Regards.

**Comment by graemeg** [comment]
Thank you for reporting this. The issue has been fixed. Please get the latest code from the git repo. :-)
